// <auto-generated />
using System;
using Cultiv.EnvironmentInspect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cultiv.EnvironmentInspect.Migrations
{
    [DbContext(typeof(EnvironmentInspectDbContext))]
    partial class EnvironmentInspectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Cultiv.EnvironmentInspect.Data.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:Identity", "1, 1")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsStarred");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("StringValue")
                        .HasMaxLength(2000);

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UserKey", "SettingKey")
                        .IsUnique();

                    b.ToTable("CultivEnvironmentInspectUserPreferences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
