<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="..\buildMultiTargeting\Cultiv.EnvironmentInspect.props" />
	<ItemGroup>
		<UmbracoJsonSchemaFiles Include="$(MSBuildThisFileDirectory)..\appsettings-schema.Cultiv.EnvironmentInspect.json" Weight="-50" />
	</ItemGroup>
</Project>
