name: Build and Package

env:
  PATH_TO_EXTENSION: "Cultiv.EnvironmentInspect"
  PATH_TO_TESTSITE: "Cultiv.EnvironmentInspect.DemoSite"
  DOTNET_VERSION: '10'

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0
        
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: false
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            conventional-changelog-conventionalcommits

      - name: Echo the version
        run: |
          echo "New release version: '${{ steps.semantic.outputs.new_release_version }}'"
          echo "New release major: '${{ steps.semantic.outputs.new_release_major_version }}'"
          echo "New release minor: '${{ steps.semantic.outputs.new_release_minor_version }}'"
          echo "New release patch: '${{ steps.semantic.outputs.new_release_patch_version }}'"
          echo "Last release version: '${{ steps.semantic.outputs.last_release_version }}'"
          echo "New release published: '${{ steps.semantic.outputs.new_release_published }}'"
  
  build:
    name: Build, Run, CodeGen and Package
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Build Client
      working-directory: ${{ env.PATH_TO_EXTENSION }}
      run: |
        cd Client
        npm i

    - name: Cache NuGet
      id: nuget-packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-cache-${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*') }}
        restore-keys: |
          nuget-cache-${{ runner.os }}-nuget-

    - name: Update umbraco-package.json version
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      working-directory: ${{ env.PATH_TO_EXTENSION }}
      run: |
        jq '.version = "${{ needs.setup.outputs.semver }}"' Client/public/umbraco-package.json > temp.json && mv temp.json Client/public/umbraco-package.json

    - name: Build Project
      working-directory: ${{ env.PATH_TO_TESTSITE }}
      run: dotnet build -c Release   

    - name: Start Project
      working-directory: ${{ github.workspace }}/${{ env.PATH_TO_TESTSITE }}
      shell: pwsh
      run: |
        $MyProcess = Start-Process -FilePath 'dotnet' -WorkingDirectory . -ArgumentList 'run --no-build --no-restore -c Release' -PassThru
        echo "DOTNET_PID=$($MyProcess.Id)" >> $env:GITHUB_ENV
        Start-Sleep -Seconds 30

    - name: CodeGen
      working-directory: ${{ env.PATH_TO_EXTENSION }}
      run: |
        cd Client
        sleep 10s
        npm run generate-client

    - name: Stop Project
      working-directory: ${{ github.workspace }}/${{ env.PATH_TO_TESTSITE }}
      shell: pwsh
      run: |
         Stop-Process -Id $env:DOTNET_PID
         
    - name: Build Client
      working-directory: ${{ env.PATH_TO_EXTENSION }}
      run: |
        cd Client
        npm run build        

    - name: Build sln
      run: dotnet build ${{ github.workspace }}/*.slnx -c Release        

    - name: pack
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      working-directory: ${{ env.PATH_TO_EXTENSION }}
      run: dotnet pack --configuration Release /p:PackageVersion=${{ needs.setup.outputs.semver }}
    
    - name: Login
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nul800sebastiaan/index.json"

    - name: push
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      run: dotnet nuget push "${{ env.PATH_TO_EXTENSION }}/bin/Release/Cultiv.EnvironmentInspect.*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
      
