name: Build and package

env:
  PATH_TO_CSPROJ: "Cultiv.EnvironmentInspect"
  PATH_TO_CLIENT: "Cultiv.EnvironmentInspect.Client"
  PATH_TO_TESTSITE: "Cultiv.EnvironmentInspect.TestSite"
  DOTNET_VERSION: '9'

on:
  push:
    branches: ["main/v1", "main/v2"]

  workflow_dispatch:

jobs:
  setup:
    name: Setup our build
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semantic.outputs.new_release_version }}


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
        
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/commit-analyzer
            @semantic-release/github

      - name: Can we echo the version
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Client
      working-directory: ${{ env.PATH_TO_CLIENT }}
      run: |
        npm i

    - name: Cache NuGet
      id: nuget-packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-cache-${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*') }}
        restore-keys: |
          nuget-cache-${{ runner.os }}-nuget-

    - name: Build sln
      run: dotnet build ${{ github.workspace }}/*.sln -c Release

    - name: Start Project
      working-directory: ${{ github.workspace }}/${{ env.PATH_TO_TESTSITE }}
      shell: pwsh
      run: |
        $MyProcess = Start-Process -FilePath 'dotnet' -WorkingDirectory . -ArgumentList 'run --no-build --no-restore -c Release' -PassThru

    - name: CodeGen
      working-directory: ${{ env.PATH_TO_CLIENT }}
      run: |
        sleep 10s
        npm run generate
        npm run build

    - name: pack
      working-directory: ${{ env.PATH_TO_CSPROJ }}
      run: dotnet pack --configuration Release
    
    - name: Login
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nul800sebastiaan/index.json"

    - name: push
      run: dotnet nuget push "${{ env.PATH_TO_CSPROJ }}/bin/Release/Cultiv.EnvironmentInspect.*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
      
